# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yarc = {
    pname = "yarc";
    version = "v1.2.0";
    src = fetchurl {
      url = "https://github.com/YARC-Official/YARC-Launcher/releases/download/v1.2.0/YARC.Launcher_1.2.0_amd64.AppImage";
      sha256 = "sha256-/RVbCdQlLU9SXXSUGY2pEs2Qgbwts023U8qYFqx6oQ4=";
    };
  };
}
